expr 
    = const
    | ident
    | "(" expr ")"
    | expr expr 
    | expr binop expr
    | "-" expr
    | "fun" pattern "->" expr
    | "let" let_binding expr "in" expr;

binop = "+" | "-" | "/" | "*";

ident = alpha alphaNum* "'"*;

let_binding 
    = pattern "=" expr
    | ident (parameter)+;

const 
    = digit*
    | "\"" ( ^\" )*  "\"";